/**
 * Server-side in-memory activity ring buffer.
 *
 * Holds the most recent N events generated by the AI / audit pipelines so the
 * landing page can render a live activity feed without persistence. The
 * buffer resets on every cold start; that's deliberate — we want
 * "live-looking" recent activity, not durable storage. Durable storage
 * belongs in Supabase (`audit_logs` table).
 *
 * IMPORTANT: This module is intended for Vercel Node.js runtime only. Edge
 * runtime does not preserve module-level state across requests within a
 * single worker the way Node does.
 */

export type ActivityEventType =
  | "candidate_generated"
  | "report_generated"
  | "simulation_built"
  | "audit_anchored";

export interface ActivityEvent {
  id: string;
  type: ActivityEventType;
  timestamp: string;
  candidate_id?: string;
  candidate_name?: string;
  x_score?: number;
  chemical_family?: string;
  hash?: string;
  /** Solana transaction signature when audit is anchored on chain. */
  tx_signature?: string;
}

const MAX_EVENTS = 30;

// Module-level state — survives within a single Vercel Node worker.
const ringBuffer: ActivityEvent[] = [];

export function recordActivity(
  event: Omit<ActivityEvent, "id" | "timestamp"> & {
    id?: string;
    timestamp?: string;
  },
): ActivityEvent {
  const full: ActivityEvent = {
    id:
      event.id ??
      `evt-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`,
    timestamp: event.timestamp ?? new Date().toISOString(),
    ...event,
  };
  ringBuffer.unshift(full);
  if (ringBuffer.length > MAX_EVENTS) {
    ringBuffer.length = MAX_EVENTS;
  }
  return full;
}

export function readActivity(limit = 10): ActivityEvent[] {
  return ringBuffer.slice(0, Math.min(limit, MAX_EVENTS));
}

export function clearActivity(): void {
  ringBuffer.length = 0;
}
